### PR TITLE
Moving to a directory instead of a jar.

### PR DESCRIPTION
**Pull request by JasonMorgan**
by just giving tbs the directory it'll pickup any jar file. You can see an example here: https://github.com/JasonMorgan/tanzu-e2e/blob/main/ci/tasks/handoff-to-tbs.sh

If y'all want to see an example holler at me. I run an example pipeline @ ci.59s.io.

This PR should address Issue #5

### CODE REVIEW

**Comment by cdelashmutt-pivotal** [comment]
Could we amend this PR a bit to limit it to only pull in the pattern of target/spring-petclinic-*.jar ?  That would make sure nothing extra would get pulled into TBS that isn't needed.

Additionally, we're working on an alternative flow that skips Concourse CI altogether.  That would eventually make this issue moot, but I'm glad to merge this in if we can see if that above pattern would work.

**Comment by mshahat** [comment]
having an example CI presented through Concourse visually was a nice element during the demo. just a feedback piece.  Thanks,

**Comment by JasonMorgan** [comment]
Hey sorry I let this go stale. Do we still want this functionality or should i close the PR? I imagine this has been OBE at this point.

**Comment by cdelashmutt-pivotal** [comment]
I _think_ we've resolved this one in main.  We now make the reference to the spring-petclinic jar as a wildcard reference.  If you don't think that is appropriate, let's open another issue.

**Pull request closed without merging**
